package ma.rest.spring.controllers;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-12-13T02:35:47.436+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://controllers.spring.rest.ma/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "customerById", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.CustomerById")
    @ResponseWrapper(localName = "customerByIdResponse", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.CustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ma.rest.spring.controllers.Customer customerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "customerList", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.CustomerList")
    @ResponseWrapper(localName = "customerListResponse", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.CustomerListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ma.rest.spring.controllers.Customer> customerList()
;

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://controllers.spring.rest.ma/", className = "ma.rest.spring.controllers.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ma.rest.spring.controllers.Customer saveCustomer(

        @WebParam(name = "customer", targetNamespace = "")
        ma.rest.spring.controllers.CustomerRequest customer
    );
}
